name: Compile LaTeX
on:
  push:
    tags:
      - '**'

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compilation
        uses: dante-ev/latex-action@latest
        with:
          root_file: slides.tex
          compiler: latexmk
          args: -pdf
      - name: Create release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: slides.pdf
          asset_name: 'Oleh Shkalikov CLSS.pdf'
          overwrite: true
          body: "Slides for the Computational Life Science Seminar at TU Dresden (SS 2023)"